import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Play, Code, CheckCircle, RefreshCw, Globe, Layout, Send, Mic, Download, ExternalLink } from 'lucide-react';
import { useScrollAnimation } from '../hooks/useScrollAnimation';

// Type-safe workaround for Framer Motion 10 + React 19 conflict
const MotionDiv = motion.div as any;
const MotionH2 = motion.h2 as any;
const MotionH3 = motion.h3 as any;
const MotionButton = motion.button as any;

const variants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0 }
};

export const Demo: React.FC = () => {
    const [prompt, setPrompt] = useState('full stack SaaS app');
    const [isExecuting, setIsExecuting] = useState(false);
    const [progress, setProgress] = useState(0);
    const [view, setView] = useState<'preview' | 'code'>('preview');
    const [showResult, setShowResult] = useState(true);
    const { ref, inView } = useScrollAnimation();

    const handleExecute = () => {
        if (isExecuting) return;
        setIsExecuting(true);
        setProgress(0);
        setShowResult(false);

        const interval = setInterval(() => {
            setProgress(prev => {
                if (prev >= 100) {
                    clearInterval(interval);
                    setIsExecuting(false);
                    setShowResult(true);
                    return 100;
                }
                return prev + Math.random() * 20;
            });
        }, 100);
    };

    const getMockCode = () => {
        return `// Generated by Laxmana AI
import React from 'react';

export const App = () => {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-white text-slate-900 p-8 font-sans">
      <h1 className="text-4xl md:text-6xl font-black mb-6 tracking-tight text-slate-900">
        ${prompt}
      </h1>
      <p className="text-slate-500 max-w-md text-center text-lg mb-10 leading-relaxed">
        This is a live preview of the application generated by Laxmana AI based on your prompt.
      </p>
      <button className="px-8 py-3 bg-[#2563eb] hover:bg-[#1d4ed8] text-white font-semibold rounded-lg transition-all shadow-md">
        Interactive Element
      </button>
    </div>
  );
};`;
    };

    return (
        <section id="demo" className="section-padding bg-[#0a0a0f] relative overflow-hidden">
            {/* Background Orbs */}
            <div className="absolute top-1/4 -left-20 w-96 h-96 bg-cyan-400/10 rounded-full blur-[120px]" />
            <div className="absolute bottom-1/4 -right-20 w-96 h-96 bg-purple-500/10 rounded-full blur-[120px]" />

            <div className="container relative z-10">
                <div className="text-center max-w-3xl mx-auto mb-16">
                    <MotionH2
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: true }}
                        variants={variants}
                        className="text-3xl md:text-5xl font-bold mb-6"
                    >
                        Experience the <span className="gradient-text">Power of Choice</span>
                    </MotionH2>
                    <p className="text-white/60 text-lg">
                        Describe what you want to build, and watch Laxmana AI architect, code, and deploy your vision in real-time.
                    </p>
                </div>

                <div
                    ref={ref as any}
                    className="grid lg:grid-cols-12 gap-8 items-start"
                >
                    {/* Controls Side */}
                    <MotionDiv
                        variants={variants}
                        initial="hidden"
                        animate={inView ? "visible" : "hidden"}
                        className="lg:col-span-12 xl:col-span-5 space-y-6"
                    >
                        <div className="glass-card p-6 min-h-[480px] flex flex-col">
                            <div className="flex items-center gap-2 text-xs font-bold text-white/40 uppercase tracking-widest mb-6 border-b border-white/5 pb-4">
                                <span className="text-cyan-400">#</span> Prompt Input
                            </div>

                            <div className="flex-1 flex flex-col gap-4">
                                <textarea
                                    value={prompt}
                                    onChange={(e) => setPrompt(e.target.value)}
                                    placeholder="Describe your application..."
                                    className="w-full h-full bg-transparent text-white placeholder:text-white/20 focus:outline-none transition-colors resize-none text-lg leading-relaxed font-sans"
                                />
                            </div>

                            <div className="flex gap-4 mt-6 pt-4 border-t border-white/5">
                                <button className="p-4 bg-white/5 hover:bg-white/10 rounded-2xl text-white/60 transition-all border border-white/10 group">
                                    <Mic size={24} className="group-hover:scale-110 transition-transform" />
                                </button>
                                <button
                                    onClick={handleExecute}
                                    disabled={isExecuting || !prompt.trim()}
                                    className={`flex-1 py-4 rounded-2xl font-black text-lg flex items-center justify-center gap-3 transition-all ${isExecuting
                                            ? 'bg-white/5 text-white/40 cursor-not-allowed'
                                            : 'bg-cyan-400 text-black shadow-lg shadow-cyan-400/20 hover:scale-[1.02] active:scale-[0.98]'
                                        }`}
                                >
                                    {isExecuting ? <RefreshCw size={22} className="animate-spin" /> : <>Execute Request <Send size={20} /></>}
                                </button>
                            </div>
                        </div>
                    </MotionDiv>

                    {/* Preview Side */}
                    <MotionDiv
                        variants={variants}
                        initial="hidden"
                        animate={inView ? "visible" : "hidden"}
                        className="lg:col-span-12 xl:col-span-7"
                    >
                        <div className="glass-card overflow-hidden flex flex-col h-[520px] shadow-2xl border-white/10 group/browser">
                            {/* Browser-like Header */}
                            <div className="bg-[#12121a] border-b border-white/10 p-4 flex items-center justify-between">
                                <div className="flex items-center gap-6">
                                    <div className="flex gap-2">
                                        <div className="w-3 h-3 rounded-full bg-[#ff5f56]" />
                                        <div className="w-3 h-3 rounded-full bg-[#ffbd2e]" />
                                        <div className="w-3 h-3 rounded-full bg-[#27c93f]" />
                                    </div>
                                    <div className="hidden md:flex items-center gap-2 bg-black/40 px-6 py-2 rounded-lg border border-white/5 text-[11px] font-mono text-white/40 w-[400px]">
                                        <Globe size={14} className="text-white/20" />
                                        https://laxmana-generated-app.local
                                    </div>
                                </div>
                                <div className="flex items-center gap-1 bg-white/5 p-1 rounded-xl">
                                    <button
                                        onClick={() => setView('preview')}
                                        className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-bold transition-all ${view === 'preview' ? 'bg-white/10 text-white' : 'text-white/40 hover:text-white'
                                            }`}
                                    >
                                        <Layout size={14} /> Preview
                                    </button>
                                    <button
                                        onClick={() => setView('code')}
                                        className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-bold transition-all ${view === 'code' ? 'bg-white/10 text-white' : 'text-white/40 hover:text-white'
                                            }`}
                                    >
                                        <Code size={14} /> Code
                                    </button>
                                </div>
                            </div>

                            {/* Content Area */}
                            <div className="flex-1 relative bg-white overflow-hidden group/content">
                                <AnimatePresence mode="wait">
                                    {isExecuting ? (
                                        <MotionDiv
                                            key="executing"
                                            initial={{ opacity: 0 }}
                                            animate={{ opacity: 1 }}
                                            exit={{ opacity: 0 }}
                                            className="absolute inset-0 flex items-center justify-center flex-col gap-8 bg-[#0a0a0f]"
                                        >
                                            <div className="relative">
                                                <div className="w-24 h-24 rounded-full border-[3px] border-cyan-400/10 animate-spin border-t-cyan-400" />
                                                <div className="absolute inset-0 flex items-center justify-center font-mono text-lg font-bold text-cyan-400">
                                                    {Math.round(progress)}%
                                                </div>
                                            </div>
                                            <div className="text-center space-y-4">
                                                <div className="font-mono text-cyan-400 text-sm animate-pulse tracking-widest uppercase font-bold">Initializing Engine...</div>
                                                <div className="px-12">
                                                    <div className="w-64 h-1.5 bg-white/5 rounded-full overflow-hidden">
                                                        <MotionDiv
                                                            animate={{ width: `${progress}%` }}
                                                            className="h-full bg-gradient-to-r from-cyan-400 to-purple-500"
                                                        />
                                                    </div>
                                                </div>
                                            </div>
                                        </MotionDiv>
                                    ) : showResult ? (
                                        view === 'preview' ? (
                                            <MotionDiv
                                                key="preview-content"
                                                initial={{ opacity: 0, scale: 0.98 }}
                                                animate={{ opacity: 1, scale: 1 }}
                                                className="h-full flex flex-col items-center justify-center p-12 text-center bg-white"
                                            >
                                                <MotionH3
                                                    initial={{ opacity: 0, y: 20 }}
                                                    animate={{ opacity: 1, y: 0 }}
                                                    className="text-4xl md:text-6xl font-black mb-6 text-slate-900 tracking-tight"
                                                >
                                                    {prompt}
                                                </MotionH3>
                                                <p className="text-slate-500 max-w-lg mb-12 leading-relaxed text-lg">
                                                    This is a live preview of the application generated by Laxmana AI based on your prompt.
                                                </p>
                                                <MotionButton
                                                    whileHover={{ scale: 1.05 }}
                                                    whileTap={{ scale: 0.95 }}
                                                    className="px-10 py-4 bg-[#2563eb] hover:bg-[#1d4ed8] text-white font-bold rounded-xl transition-all shadow-xl shadow-blue-600/20"
                                                >
                                                    Interactive Element
                                                </MotionButton>

                                                {/* Floating Actions like in screenshot */}
                                                <div className="absolute bottom-6 right-6 flex items-center gap-3 animate-in fade-in slide-in-from-bottom-4 duration-700">
                                                    <button className="flex items-center gap-2 px-4 py-2 bg-[#1a1a25] text-white rounded-lg text-sm font-bold border border-white/5 hover:bg-white/10 transition-all">
                                                        <Download size={14} /> Export
                                                    </button>
                                                    <button className="flex items-center gap-2 px-4 py-2 bg-cyan-400 text-black rounded-lg text-sm font-black shadow-lg shadow-cyan-400/20 hover:scale-105 transition-all">
                                                        <ExternalLink size={14} /> Deploy
                                                    </button>
                                                </div>
                                            </MotionDiv>
                                        ) : (
                                            <MotionDiv
                                                key="code-content"
                                                initial={{ opacity: 0, x: 20 }}
                                                animate={{ opacity: 1, x: 0 }}
                                                className="h-full p-8 font-mono text-sm bg-[#0a0a0f] overflow-auto"
                                            >
                                                <pre className="text-white/80 whitespace-pre-wrap">
                                                    <code className="text-cyan-400">{getMockCode()}</code>
                                                </pre>
                                            </MotionDiv>
                                        )
                                    ) : null}
                                </AnimatePresence>
                            </div>
                        </div>
                    </MotionDiv>
                </div>
            </div>
        </section>
    );
};
