import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Play, Code, CheckCircle, RefreshCw, Globe, Layout, Send } from 'lucide-react';
import { useScrollAnimation } from '../hooks/useScrollAnimation';

// Type-safe workaround for Framer Motion 10 + React 19 conflict
const MotionDiv = motion.div as any;
const MotionH2 = motion.h2 as any;
const MotionH3 = motion.h3 as any;
const MotionButton = motion.button as any;

const variants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0 }
};

export const Demo: React.FC = () => {
    const [prompt, setPrompt] = useState('hey');
    const [isExecuting, setIsExecuting] = useState(false);
    const [progress, setProgress] = useState(0);
    const [view, setView] = useState<'preview' | 'code'>('preview');
    const [showResult, setShowResult] = useState(true);
    const { ref, inView } = useScrollAnimation();

    const handleExecute = () => {
        if (isExecuting) return;
        setIsExecuting(true);
        setProgress(0);
        setShowResult(false);

        const interval = setInterval(() => {
            setProgress(prev => {
                if (prev >= 100) {
                    clearInterval(interval);
                    setIsExecuting(false);
                    setShowResult(true);
                    return 100;
                }
                return prev + Math.random() * 20;
            });
        }, 150);
    };

    const getMockCode = () => {
        return `// Generated by Laxmana AI
import React from 'react';

export const App = () => {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-[#0a0a0f] text-white p-8 font-sans">
      <h1 className="text-4xl md:text-6xl font-black mb-6 tracking-tight animate-in fade-in slide-in-from-bottom-4 duration-1000">
        ${prompt}
      </h1>
      <p className="text-slate-400 max-w-md text-center text-lg mb-10 leading-relaxed">
        This is a live preview of the application generated by Laxmana AI based on your prompt.
      </p>
      <button className="px-8 py-4 bg-cyan-400 hover:bg-cyan-500 text-black font-bold rounded-2xl transition-all shadow-lg shadow-cyan-400/20 hover:scale-105 active:scale-95">
        Interactive Element
      </button>
    </div>
  );
};`;
    };

    return (
        <section id="demo" className="section-padding bg-background relative overflow-hidden">
            {/* Background Orbs */}
            <div className="absolute top-1/4 -left-20 w-96 h-96 bg-cyan-400/10 rounded-full blur-[120px]" />
            <div className="absolute bottom-1/4 -right-20 w-96 h-96 bg-purple-500/10 rounded-full blur-[120px]" />

            <div className="container relative z-10">
                <div className="text-center max-w-3xl mx-auto mb-16">
                    <MotionH2
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: true }}
                        variants={variants}
                        className="text-3xl md:text-5xl font-bold mb-6"
                    >
                        Experience the <span className="gradient-text">Power of Choice</span>
                    </MotionH2>
                    <p className="text-white/60 text-lg">
                        Describe what you want to build, and watch Laxmana AI architect, code, and deploy your vision in real-time.
                    </p>
                </div>

                <div
                    ref={ref as any}
                    className="grid lg:grid-cols-12 gap-8 items-start"
                >
                    {/* Controls Side */}
                    <MotionDiv
                        variants={variants}
                        initial="hidden"
                        animate={inView ? "visible" : "hidden"}
                        className="lg:col-span-4 space-y-6"
                    >
                        <div className="glass-card p-6">
                            <label className="text-xs font-bold text-white/40 uppercase tracking-widest mb-4 block">Prompt Input</label>
                            <div className="relative">
                                <textarea
                                    value={prompt}
                                    onChange={(e) => setPrompt(e.target.value)}
                                    placeholder="Describe your application..."
                                    className="w-full bg-white/5 border border-white/10 rounded-xl p-4 text-white placeholder:text-white/20 focus:outline-none focus:border-cyan-400/50 transition-colors h-32 resize-none"
                                />
                                <button
                                    onClick={handleExecute}
                                    disabled={isExecuting || !prompt.trim()}
                                    className={`absolute bottom-3 right-3 p-2 rounded-lg transition-all ${isExecuting ? 'bg-white/10 text-white/40 cursor-not-allowed' : 'bg-cyan-400 text-black hover:scale-105 active:scale-95'
                                        }`}
                                >
                                    <Send size={18} />
                                </button>
                            </div>

                            <button
                                onClick={handleExecute}
                                disabled={isExecuting || !prompt.trim()}
                                className={`w-full mt-4 py-3 rounded-xl font-bold flex items-center justify-center gap-2 transition-all ${isExecuting
                                        ? 'bg-white/5 text-white/40 cursor-not-allowed'
                                        : 'bg-gradient-to-r from-cyan-400 to-purple-500 text-white shadow-lg shadow-cyan-400/20 hover:shadow-cyan-400/40'
                                    }`}
                            >
                                {isExecuting ? <RefreshCw size={18} className="animate-spin" /> : <Play size={18} />}
                                Execute Request
                            </button>
                        </div>

                        <div className="glass-card p-6">
                            <h4 className="font-bold mb-4">Live Insights</h4>
                            <div className="space-y-4">
                                <div className="flex items-center justify-between text-xs">
                                    <span className="text-white/40">Status</span>
                                    <span className={isExecuting ? 'text-amber-400' : 'text-green-400'}>
                                        {isExecuting ? 'Architecting...' : 'Ready'}
                                    </span>
                                </div>
                                <div className="w-full h-1 bg-white/5 rounded-full overflow-hidden">
                                    <MotionDiv
                                        animate={{ width: `${progress}%` }}
                                        className="h-full bg-cyan-400"
                                    />
                                </div>
                                <div className="grid grid-cols-2 gap-4">
                                    <div className="bg-white/5 rounded-lg p-3 border border-white/5">
                                        <div className="text-[10px] text-white/40 uppercase mb-1">Tokens/sec</div>
                                        <div className="font-mono text-cyan-400">2,481</div>
                                    </div>
                                    <div className="bg-white/5 rounded-lg p-3 border border-white/5">
                                        <div className="text-[10px] text-white/40 uppercase mb-1">Time Elapsed</div>
                                        <div className="font-mono text-purple-500">{isExecuting ? '0.2s' : '0.0s'}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </MotionDiv>

                    {/* Preview Side */}
                    <MotionDiv
                        variants={variants}
                        initial="hidden"
                        animate={inView ? "visible" : "hidden"}
                        className="lg:col-span-8"
                    >
                        <div className="glass-card overflow-hidden flex flex-col h-[600px] hover:border-cyan-400/30 transition-colors">
                            {/* Browser-like Header */}
                            <div className="bg-white/5 border-b border-white/10 p-4 flex items-center justify-between">
                                <div className="flex items-center gap-4">
                                    <div className="flex gap-1.5">
                                        <div className="w-3 h-3 rounded-full bg-red-400/20 border border-red-400/40" />
                                        <div className="w-3 h-3 rounded-full bg-yellow-400/20 border border-yellow-400/40" />
                                        <div className="w-3 h-3 rounded-full bg-green-400/20 border border-green-400/40" />
                                    </div>
                                    <div className="flex items-center gap-2 bg-black/40 px-4 py-1.5 rounded-full border border-white/5 text-[11px] font-mono text-white/40 w-64 md:w-96">
                                        <Globe size={12} />
                                        https://laxmana-generated-app.local
                                    </div>
                                </div>
                                <div className="flex items-center gap-1 bg-white/5 p-1 rounded-lg">
                                    <button
                                        onClick={() => setView('preview')}
                                        className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-xs font-bold transition-all ${view === 'preview' ? 'bg-cyan-400 text-black' : 'text-white/40 hover:text-white'
                                            }`}
                                    >
                                        <Layout size={14} /> Preview
                                    </button>
                                    <button
                                        onClick={() => setView('code')}
                                        className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-xs font-bold transition-all ${view === 'code' ? 'bg-cyan-400 text-black' : 'text-white/40 hover:text-white'
                                            }`}
                                    >
                                        <Code size={14} /> Code
                                    </button>
                                </div>
                            </div>

                            {/* Content Area */}
                            <div className="flex-1 relative bg-black/20 overflow-auto">
                                <AnimatePresence mode="wait">
                                    {isExecuting ? (
                                        <MotionDiv
                                            key="executing"
                                            initial={{ opacity: 0 }}
                                            animate={{ opacity: 1 }}
                                            exit={{ opacity: 0 }}
                                            className="absolute inset-0 flex items-center justify-center flex-col gap-6"
                                        >
                                            <div className="relative">
                                                <div className="w-20 h-20 rounded-full border-2 border-cyan-400/20 animate-spin border-t-cyan-400" />
                                                <div className="absolute inset-0 flex items-center justify-center font-mono text-xs text-cyan-400">
                                                    {Math.round(progress)}%
                                                </div>
                                            </div>
                                            <div className="text-center">
                                                <div className="font-mono text-cyan-400 text-sm animate-pulse tracking-widest uppercase">Executing_Logic...</div>
                                                <div className="text-[10px] text-white/30 uppercase mt-2 font-mono">Parsing system instructions</div>
                                            </div>
                                            <div className="w-full max-w-md px-8 space-y-2">
                                                <div className="h-1.5 bg-white/5 rounded-full overflow-hidden">
                                                    <MotionDiv
                                                        animate={{ width: `${progress}%` }}
                                                        className="h-full bg-gradient-to-r from-cyan-400 to-purple-500"
                                                    />
                                                </div>
                                            </div>
                                        </MotionDiv>
                                    ) : showResult ? (
                                        view === 'preview' ? (
                                            <MotionDiv
                                                key="preview-content"
                                                initial={{ opacity: 0, scale: 0.98 }}
                                                animate={{ opacity: 1, scale: 1 }}
                                                className="h-full flex flex-col items-center justify-center p-12 text-center"
                                            >
                                                <MotionH3
                                                    initial={{ opacity: 0, y: 20 }}
                                                    animate={{ opacity: 1, y: 0 }}
                                                    className="text-4xl md:text-5xl lg:text-7xl font-black mb-6 text-white tracking-tight"
                                                >
                                                    {prompt}
                                                </MotionH3>
                                                <p className="text-white/40 max-w-lg mb-10 leading-relaxed text-lg font-sans">
                                                    This is a live preview of the application generated by Laxmana AI based on your prompt.
                                                </p>
                                                <MotionButton
                                                    whileHover={{ scale: 1.05 }}
                                                    whileTap={{ scale: 0.95 }}
                                                    className="px-8 py-4 bg-white/10 hover:bg-white/20 border border-white/10 rounded-2xl font-bold transition-all text-white flex items-center gap-3 backdrop-blur-xl"
                                                >
                                                    <Layout size={20} className="text-cyan-400" />
                                                    Interactive Element
                                                </MotionButton>

                                                <div className="mt-12 flex items-center gap-2 text-xs text-white/20 font-mono">
                                                    <CheckCircle size={14} className="text-green-500/50" />
                                                    BUILD_SUCCESSFUL_v1.0.4
                                                </div>
                                            </MotionDiv>
                                        ) : (
                                            <MotionDiv
                                                key="code-content"
                                                initial={{ opacity: 0, x: 20 }}
                                                animate={{ opacity: 1, x: 0 }}
                                                className="p-8 font-mono text-sm"
                                            >
                                                <pre className="text-white/80 whitespace-pre-wrap">
                                                    <code className="text-cyan-400">{getMockCode()}</code>
                                                </pre>
                                            </MotionDiv>
                                        )
                                    ) : null}
                                </AnimatePresence>
                            </div>

                            {/* Status Bar */}
                            <div className="bg-white/5 border-t border-white/10 p-3 px-6 flex items-center justify-between text-[10px] text-white/40 uppercase tracking-widest font-mono">
                                <div className="flex items-center gap-4">
                                    <div className="flex items-center gap-1.5">
                                        <div className={`w-1.5 h-1.5 rounded-full ${isExecuting ? 'bg-amber-500 animate-pulse' : 'bg-green-500'}`} />
                                        {isExecuting ? 'Processing' : 'Connected'}
                                    </div>
                                    <span>Branch: Main</span>
                                </div>
                                <div className="flex items-center gap-4">
                                    <span>V1.4.2-STABLE</span>
                                    <span className="text-cyan-400">Port: 3000</span>
                                </div>
                            </div>
                        </div>
                    </MotionDiv>
                </div>
            </div>
        </section>
    );
};
